# Generated by Django 4.0.4 on 2022-05-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_external_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=400)),
                ('publish_year', models.CharField(max_length=4)),
                ('acquired', models.BooleanField()),
                ('thumbnail', models.CharField(max_length=600, null=True)),
                ('authors', models.ManyToManyField(related_name='books', to='stx_api.author')),
            ],
        ),
    ]
