# Generated by Django 4.0.4 on 2022-05-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stx_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
