# Generated by Django 4.0.4 on 2022-05-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stx_api', '0005_alter_book_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
