# Generated by Django 4.0.4 on 2022-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stx_api', '0006_rename_full_name_author_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='external_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
