# Generated by Django 4.0.4 on 2022-05-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stx_api', '0007_alter_book_external_id_alter_book_thumbnail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'published_year')},
        ),
    ]
