# Generated by Django 4.0.4 on 2022-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stx_api', '0011_alter_book_published_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='external_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
