# Generated by Django 4.0.4 on 2022-06-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stx_api', '0012_alter_book_external_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'external_id')},
        ),
    ]
