# Generated by Django 4.0.4 on 2022-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stx_api', '0013_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
